name: Deploy Vaultwarden

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      # إعداد Docker Buildx للكاش لسرعة بناء كمال
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # تفعيل الوصول لكاش GitHub Actions
      - name: Expose GitHub Runtime for Docker Cache
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Kamal
        run: gem install kamal -v 2.10.1

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy with Kamal
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ vars.SERVER_IP }} >> ~/.ssh/known_hosts
          kamal deploy
        env:
          SERVER_IP: ${{ vars.SERVER_IP }}
          DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          DOCKER_PA_TOKEN: ${{ secrets.DOCKER_PA_TOKEN }}
          DOCKER_BUILDKIT: 1